# Generated by Django 5.1.5 on 2026-07-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Compliant', 'Compliant'), ('Partial', 'Partial'), ('Late Entry', 'Late Entry'), ('Wrong Direction', 'Wrong Direction'), ('Missed', 'Missed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('score', models.IntegerField(default=0, help_text='0-100 compliance score')),
                ('actual_direction', models.CharField(blank=True, max_length=4, null=True)),
                ('actual_entry', models.FloatField(blank=True, null=True)),
                ('actual_entry_time', models.TimeField(blank=True, null=True)),
                ('coaching_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='signals.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_records',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'signal')},
            },
        ),
    ]
