# Generated by Django 5.1.5 on 2026-07-22 03:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('signals', '0001_initial'),
        ('mt5', '0002_trade_mt5account_deleted_at_mt5account_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplianceRecord',
            new_name='ComplianceResult',
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='trader_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_results', to='users.traderprofile'),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_compliance_result', to='mt5.trade'),
        ),
        migrations.AlterField(
            model_name='complianceresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complianceresult',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='signals.signal'),
        ),
        migrations.AlterField(
            model_name='complianceresult',
            name='status',
            field=models.CharField(choices=[('Compliant', 'Compliant'), ('Partial', 'Partial'), ('Late Entry', 'Late Entry'), ('Wrong Direction', 'Wrong Direction'), ('Missed', 'Missed'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='complianceresult',
            options={'db_table': 'compliance_records', 'ordering': ['-created_at']},
        ),
    ]
