# Generated by Django 5.1.5 on 2026-07-22 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_alter_compliancerecord_unique_together_and_more'),
        ('mt5', '0002_trade_mt5account_deleted_at_mt5account_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceresult',
            name='trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_compliance_result', to='mt5.trade'),
        ),
    ]
