# Generated by Django 5.1.5 on 2026-07-22 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_complianceresult_trade'),
        ('users', '0004_traderprofile_user_created_at_user_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['user', 'signal'], name='compliance__user_id_67bdd1_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['status', 'score'], name='compliance__status_fe9f55_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceresult',
            constraint=models.UniqueConstraint(fields=('user', 'signal'), name='uniq_compliance_result_user_signal'),
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('compliance.complianceresult',),
        ),
    ]
