# Generated by Django 5.1.5 on 2026-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_sopwarning_complianceresult_violations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sopwarning',
            new_name='sop_warning_user_id_0037d5_idx',
            old_name='sop_warn_user_idx',
        ),
        migrations.RenameIndex(
            model_name='sopwarning',
            new_name='sop_warning_violati_e21a21_idx',
            old_name='sop_warn_type_idx',
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='entry1_ticket',
            field=models.BigIntegerField(blank=True, help_text='Trade ticket at Fib 0.236', null=True),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='entry2_ticket',
            field=models.BigIntegerField(blank=True, help_text='Trade ticket at Fib 0.500', null=True),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='entry3_ticket',
            field=models.BigIntegerField(blank=True, help_text='Trade ticket at Fib 0.618', null=True),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='entry_count',
            field=models.IntegerField(default=0, help_text='How many of the 3 required entries were opened'),
        ),
        migrations.AlterField(
            model_name='sopwarning',
            name='violation_type',
            field=models.CharField(choices=[('missed_signal', 'Signal Dilewati'), ('incomplete_entries', 'Entry Kurang dari 3'), ('wrong_direction', 'Arah Salah'), ('late_entry', 'Entry Terlambat'), ('no_stop_loss', 'Tidak Ada SL'), ('no_take_profit', 'Tidak Ada TP'), ('wrong_stop_loss', 'SL Tidak Sesuai Level'), ('wrong_lot_size', 'Lot Size Salah'), ('entry_out_of_zone', 'Entry di Luar Zona'), ('multiple', 'Beberapa Pelanggaran')], max_length=30),
        ),
    ]
