# Generated by Django 5.1.5 on 2026-07-22 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Source identifier, e.g. ea', max_length=100)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'integration_receipts',
                'indexes': [models.Index(fields=['source', 'event_id'], name='integration_source_0e9cc1_idx')],
                'unique_together': {('source', 'event_id')},
            },
        ),
    ]
