# Generated by Django 5.1.5 on 2026-07-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_add_schedule_date_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('assignment_type', models.CharField(choices=[('regular', 'Regular'), ('cover', 'Cover'), ('off', 'Off')], default='regular', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'attendance_schedule_entries',
                'ordering': ['user', 'date'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendanceschedule',
            options={'ordering': ['user', 'start_date']},
        ),
        migrations.RemoveConstraint(
            model_name='attendanceschedule',
            name='uniq_attendance_schedule_user',
        ),
        migrations.AddIndex(
            model_name='attendanceschedule',
            index=models.Index(fields=['start_date', 'end_date'], name='attendance__start_d_9f11e5_idx'),
        ),
        migrations.AddField(
            model_name='attendancescheduleentry',
            name='cover_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='covered_schedule_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancescheduleentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancescheduleentry',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='attendance.attendanceshift'),
        ),
        migrations.AddField(
            model_name='attendancescheduleentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_schedule_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendancescheduleentry',
            index=models.Index(fields=['date'], name='attendance__date_124a42_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancescheduleentry',
            index=models.Index(fields=['assignment_type'], name='attendance__assignm_f660b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancescheduleentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_attendance_schedule_entry_user_date'),
        ),
    ]
