# Generated by Django 5.1.5 on 2026-07-23 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancescheduleentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='uniq_attendance_record_user_date',
        ),
        migrations.RemoveConstraint(
            model_name='attendancescheduleentry',
            name='uniq_attendance_schedule_entry_user_date',
        ),
        migrations.AlterField(
            model_name='attendanceschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'shift'), name='uniq_attendance_record_user_date_shift'),
        ),
        migrations.AddConstraint(
            model_name='attendancescheduleentry',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'shift'), name='uniq_attendance_schedule_entry_user_date_shift'),
        ),
        migrations.AddConstraint(
            model_name='attendancescheduleentry',
            constraint=models.UniqueConstraint(condition=models.Q(('shift__isnull', True)), fields=('user', 'date'), name='uniq_attendance_schedule_entry_user_date_off'),
        ),
    ]
