# Generated by Django 5.1.5 on 2026-07-21 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.BigIntegerField(help_text='MT5 account login number')),
                ('password_encrypted', models.CharField(help_text='Encrypted MT5 password', max_length=512)),
                ('server', models.CharField(help_text='Broker server name e.g. ICMarkets-Live01', max_length=100)),
                ('broker', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Display account number', max_length=50)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0)),
                ('equity', models.FloatField(default=0)),
                ('floating_pnl', models.FloatField(default=0)),
                ('margin', models.FloatField(default=0)),
                ('free_margin', models.FloatField(default=0)),
                ('margin_level', models.FloatField(default=0)),
                ('margin_call_level', models.FloatField(default=0)),
                ('drawdown', models.FloatField(default=0)),
                ('open_positions', models.IntegerField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('leverage', models.IntegerField(default=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mt5_accounts',
            },
        ),
        migrations.CreateModel(
            name='MT5Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField()),
                ('order', models.BigIntegerField(default=0)),
                ('symbol', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=4)),
                ('entry', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('INOUT', 'In/Out'), ('OUT_BY', 'Out By')], default='IN', max_length=10)),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('profit', models.FloatField(default=0)),
                ('swap', models.FloatField(default=0)),
                ('commission', models.FloatField(default=0)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('magic', models.BigIntegerField(default=0)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='mt5.mt5account')),
            ],
            options={
                'db_table': 'mt5_deals',
                'ordering': ['-time'],
                'unique_together': {('account', 'ticket')},
            },
        ),
        migrations.CreateModel(
            name='MT5Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('volume', models.FloatField()),
                ('price_open', models.FloatField()),
                ('sl', models.FloatField(blank=True, null=True)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('magic', models.BigIntegerField(default=0)),
                ('time_setup', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mt5.mt5account')),
            ],
            options={
                'db_table': 'mt5_orders',
                'unique_together': {('account', 'ticket')},
            },
        ),
        migrations.CreateModel(
            name='MT5Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('volume', models.FloatField(help_text='Lot size')),
                ('price_open', models.FloatField()),
                ('price_current', models.FloatField(default=0)),
                ('sl', models.FloatField(blank=True, null=True)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(default=0)),
                ('swap', models.FloatField(default=0)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('magic', models.BigIntegerField(default=0)),
                ('time_open', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='mt5.mt5account')),
            ],
            options={
                'db_table': 'mt5_positions',
                'unique_together': {('account', 'ticket')},
            },
        ),
    ]
