# Generated by Django 5.1.5 on 2026-07-22 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_complianceresult_trader_profile_and_more'),
        ('mt5', '0002_trade_mt5account_deleted_at_mt5account_deleted_by_and_more'),
        ('signals', '0002_tradingsignal_signal_assigned_to_signal_deleted_at_and_more'),
        ('users', '0004_traderprofile_user_created_at_user_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='trader_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mt5_account', to='users.traderprofile'),
        ),
        migrations.AddIndex(
            model_name='mt5account',
            index=models.Index(fields=['status', 'is_demo'], name='mt5_account_status_39bf70_idx'),
        ),
        migrations.AddIndex(
            model_name='mt5account',
            index=models.Index(fields=['broker', 'server'], name='mt5_account_broker_525adf_idx'),
        ),
        migrations.AddConstraint(
            model_name='mt5account',
            constraint=models.UniqueConstraint(fields=('login', 'broker'), name='uniq_mt5_account_login_broker'),
        ),
        migrations.AddField(
            model_name='trade',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='mt5.mt5account'),
        ),
        migrations.AddField(
            model_name='trade',
            name='compliance_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_links', to='compliance.complianceresult'),
        ),
        migrations.AddField(
            model_name='trade',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='signals.signal'),
        ),
        migrations.AddField(
            model_name='trade',
            name='trader_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='users.traderprofile'),
        ),
        migrations.AddField(
            model_name='trade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', 'status'], name='trades_account_63f66f_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', 'open_time'], name='trades_symbol_490a6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('account', 'ticket'), name='uniq_trade_account_ticket'),
        ),
    ]
