# Generated by Django 5.1.5 on 2026-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0003_mt5account_trader_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='SL price at time of entry', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='TP price at time of entry', max_digits=12, null=True),
        ),
    ]
