# Generated by Django 5.1.5 on 2026-07-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0004_trade_stop_loss_trade_take_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Kapan order dibatalkan (untuk pending yang tidak tersentuh)', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market Order'), ('buy_limit', 'Buy Limit'), ('sell_limit', 'Sell Limit'), ('buy_stop', 'Buy Stop'), ('sell_stop', 'Sell Stop')], default='market', help_text='SOP: harus buy_limit atau sell_limit', max_length=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
