/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TraderRouteImport } from './routes/trader'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminChartRouteImport } from './routes/admin.chart'
import { Route as AdminComplianceRouteImport } from './routes/admin.compliance'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminMt5RouteImport } from './routes/admin.mt5'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTradersRouteImport } from './routes/admin.traders'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as TraderIndexRouteImport } from './routes/trader.index'
import { Route as TraderAttendanceRouteImport } from './routes/trader.attendance'
import { Route as TraderChartRouteImport } from './routes/trader.chart'
import { Route as TraderChecklistRouteImport } from './routes/trader.checklist'
import { Route as TraderMt5RouteImport } from './routes/trader.mt5'
import { Route as TraderProfileRouteImport } from './routes/trader.profile'
import { Route as TraderReportRouteImport } from './routes/trader.report'
import { Route as TraderSignalsRouteImport } from './routes/trader.signals'
import { Route as AdminSignalsIndexRouteImport } from './routes/admin.signals.index'
import { Route as AdminSignalsIdRouteImport } from './routes/admin.signals.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TraderRoute = TraderRouteImport.update({
  id: '/trader',
  path: '/trader',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChartRoute = AdminChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMt5Route = AdminMt5RouteImport.update({
  id: '/mt5',
  path: '/mt5',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTradersRoute = AdminTradersRouteImport.update({
  id: '/traders',
  path: '/traders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const TraderIndexRoute = TraderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TraderRoute,
} as any)
const TraderAttendanceRoute = TraderAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TraderRoute,
} as any)
const TraderChartRoute = TraderChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => TraderRoute,
} as any)
const TraderChecklistRoute = TraderChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => TraderRoute,
} as any)
const TraderMt5Route = TraderMt5RouteImport.update({
  id: '/mt5',
  path: '/mt5',
  getParentRoute: () => TraderRoute,
} as any)
const TraderProfileRoute = TraderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TraderRoute,
} as any)
const TraderReportRoute = TraderReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => TraderRoute,
} as any)
const TraderSignalsRoute = TraderSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => TraderRoute,
} as any)
const AdminSignalsIndexRoute = AdminSignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignalsIdRoute = AdminSignalsIdRouteImport.update({
  id: '/signals/$id',
  path: '/signals/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/trader': typeof TraderRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/chart': typeof AdminChartRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/mt5': typeof AdminMt5Route
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/traders': typeof AdminTradersRoute
  '/admin/users': typeof AdminUsersRoute
  '/trader/attendance': typeof TraderAttendanceRoute
  '/trader/chart': typeof TraderChartRoute
  '/trader/checklist': typeof TraderChecklistRoute
  '/trader/mt5': typeof TraderMt5Route
  '/trader/profile': typeof TraderProfileRoute
  '/trader/report': typeof TraderReportRoute
  '/trader/signals': typeof TraderSignalsRoute
  '/admin/': typeof AdminIndexRoute
  '/trader/': typeof TraderIndexRoute
  '/admin/signals/$id': typeof AdminSignalsIdRoute
  '/admin/signals/': typeof AdminSignalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/chart': typeof AdminChartRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/mt5': typeof AdminMt5Route
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/traders': typeof AdminTradersRoute
  '/admin/users': typeof AdminUsersRoute
  '/trader/attendance': typeof TraderAttendanceRoute
  '/trader/chart': typeof TraderChartRoute
  '/trader/checklist': typeof TraderChecklistRoute
  '/trader/mt5': typeof TraderMt5Route
  '/trader/profile': typeof TraderProfileRoute
  '/trader/report': typeof TraderReportRoute
  '/trader/signals': typeof TraderSignalsRoute
  '/admin': typeof AdminIndexRoute
  '/trader': typeof TraderIndexRoute
  '/admin/signals/$id': typeof AdminSignalsIdRoute
  '/admin/signals': typeof AdminSignalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/trader': typeof TraderRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/chart': typeof AdminChartRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/mt5': typeof AdminMt5Route
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/traders': typeof AdminTradersRoute
  '/admin/users': typeof AdminUsersRoute
  '/trader/attendance': typeof TraderAttendanceRoute
  '/trader/chart': typeof TraderChartRoute
  '/trader/checklist': typeof TraderChecklistRoute
  '/trader/mt5': typeof TraderMt5Route
  '/trader/profile': typeof TraderProfileRoute
  '/trader/report': typeof TraderReportRoute
  '/trader/signals': typeof TraderSignalsRoute
  '/admin/': typeof AdminIndexRoute
  '/trader/': typeof TraderIndexRoute
  '/admin/signals/$id': typeof AdminSignalsIdRoute
  '/admin/signals/': typeof AdminSignalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/trader'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/chart'
    | '/admin/compliance'
    | '/admin/leaderboard'
    | '/admin/mt5'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/traders'
    | '/admin/users'
    | '/trader/attendance'
    | '/trader/chart'
    | '/trader/checklist'
    | '/trader/mt5'
    | '/trader/profile'
    | '/trader/report'
    | '/trader/signals'
    | '/admin/'
    | '/trader/'
    | '/admin/signals/$id'
    | '/admin/signals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/chart'
    | '/admin/compliance'
    | '/admin/leaderboard'
    | '/admin/mt5'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/traders'
    | '/admin/users'
    | '/trader/attendance'
    | '/trader/chart'
    | '/trader/checklist'
    | '/trader/mt5'
    | '/trader/profile'
    | '/trader/report'
    | '/trader/signals'
    | '/admin'
    | '/trader'
    | '/admin/signals/$id'
    | '/admin/signals'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/trader'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/chart'
    | '/admin/compliance'
    | '/admin/leaderboard'
    | '/admin/mt5'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/traders'
    | '/admin/users'
    | '/trader/attendance'
    | '/trader/chart'
    | '/trader/checklist'
    | '/trader/mt5'
    | '/trader/profile'
    | '/trader/report'
    | '/trader/signals'
    | '/admin/'
    | '/trader/'
    | '/admin/signals/$id'
    | '/admin/signals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  TraderRoute: typeof TraderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trader': {
      id: '/trader'
      path: '/trader'
      fullPath: '/trader'
      preLoaderRoute: typeof TraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chart': {
      id: '/admin/chart'
      path: '/chart'
      fullPath: '/admin/chart'
      preLoaderRoute: typeof AdminChartRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mt5': {
      id: '/admin/mt5'
      path: '/mt5'
      fullPath: '/admin/mt5'
      preLoaderRoute: typeof AdminMt5RouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traders': {
      id: '/admin/traders'
      path: '/traders'
      fullPath: '/admin/traders'
      preLoaderRoute: typeof AdminTradersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trader/': {
      id: '/trader/'
      path: '/'
      fullPath: '/trader/'
      preLoaderRoute: typeof TraderIndexRouteImport
      parentRoute: typeof TraderRoute
    }
    '/trader/attendance': {
      id: '/trader/attendance'
      path: '/attendance'
      fullPath: '/trader/attendance'
      preLoaderRoute: typeof TraderAttendanceRouteImport
      parentRoute: typeof TraderRoute
    }
    '/trader/chart': {
      id: '/trader/chart'
      path: '/chart'
      fullPath: '/trader/chart'
      preLoaderRoute: typeof TraderChartRouteImport
      parentRoute: typeof TraderRoute
    }
    '/trader/checklist': {
      id: '/trader/checklist'
      path: '/checklist'
      fullPath: '/trader/checklist'
      preLoaderRoute: typeof TraderChecklistRouteImport
      parentRoute: typeof TraderRoute
    }
    '/trader/mt5': {
      id: '/trader/mt5'
      path: '/mt5'
      fullPath: '/trader/mt5'
      preLoaderRoute: typeof TraderMt5RouteImport
      parentRoute: typeof TraderRoute
    }
    '/trader/profile': {
      id: '/trader/profile'
      path: '/profile'
      fullPath: '/trader/profile'
      preLoaderRoute: typeof TraderProfileRouteImport
      parentRoute: typeof TraderRoute
    }
    '/trader/report': {
      id: '/trader/report'
      path: '/report'
      fullPath: '/trader/report'
      preLoaderRoute: typeof TraderReportRouteImport
      parentRoute: typeof TraderRoute
    }
    '/trader/signals': {
      id: '/trader/signals'
      path: '/signals'
      fullPath: '/trader/signals'
      preLoaderRoute: typeof TraderSignalsRouteImport
      parentRoute: typeof TraderRoute
    }
    '/admin/signals/': {
      id: '/admin/signals/'
      path: '/signals'
      fullPath: '/admin/signals/'
      preLoaderRoute: typeof AdminSignalsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signals/$id': {
      id: '/admin/signals/$id'
      path: '/signals/$id'
      fullPath: '/admin/signals/$id'
      preLoaderRoute: typeof AdminSignalsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminChartRoute: typeof AdminChartRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminMt5Route: typeof AdminMt5Route
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTradersRoute: typeof AdminTradersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSignalsIdRoute: typeof AdminSignalsIdRoute
  AdminSignalsIndexRoute: typeof AdminSignalsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminChartRoute: AdminChartRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminMt5Route: AdminMt5Route,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTradersRoute: AdminTradersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSignalsIdRoute: AdminSignalsIdRoute,
  AdminSignalsIndexRoute: AdminSignalsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TraderRouteChildren {
  TraderAttendanceRoute: typeof TraderAttendanceRoute
  TraderChartRoute: typeof TraderChartRoute
  TraderChecklistRoute: typeof TraderChecklistRoute
  TraderMt5Route: typeof TraderMt5Route
  TraderProfileRoute: typeof TraderProfileRoute
  TraderReportRoute: typeof TraderReportRoute
  TraderSignalsRoute: typeof TraderSignalsRoute
  TraderIndexRoute: typeof TraderIndexRoute
}

const TraderRouteChildren: TraderRouteChildren = {
  TraderAttendanceRoute: TraderAttendanceRoute,
  TraderChartRoute: TraderChartRoute,
  TraderChecklistRoute: TraderChecklistRoute,
  TraderMt5Route: TraderMt5Route,
  TraderProfileRoute: TraderProfileRoute,
  TraderReportRoute: TraderReportRoute,
  TraderSignalsRoute: TraderSignalsRoute,
  TraderIndexRoute: TraderIndexRoute,
}

const TraderRouteWithChildren =
  TraderRoute._addFileChildren(TraderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  TraderRoute: TraderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
