# Generated by Django 5.1.5 on 2026-07-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', help_text='TradingView ticker e.g. OANDA:XAUUSD', max_length=30)),
                ('pair', models.CharField(help_text='Short pair e.g. XAUUSD', max_length=20)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('timeframe', models.CharField(default='15', help_text='e.g. 1, 5, 15, 60, 240, D', max_length=10)),
                ('strategy_name', models.CharField(blank=True, default='Fibonacci Strategy', max_length=100)),
                ('fib_entry', models.FloatField(help_text='Fibonacci entry level e.g. 0.236, 0.5, 0.618')),
                ('take_profit', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('fib_0236', models.FloatField(blank=True, null=True)),
                ('fib_0500', models.FloatField(blank=True, null=True)),
                ('fib_0618', models.FloatField(blank=True, null=True)),
                ('fib_tp', models.FloatField(blank=True, help_text='Fib extension TP level (-0.27)', null=True)),
                ('issued_at', models.TimeField(help_text='Signal time HH:MM')),
                ('session_date', models.DateField(help_text='Trading date')),
                ('max_entry_time', models.TimeField(help_text='Max time to enter')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Waiting', 'Waiting'), ('Executed', 'Executed'), ('Late', 'Late'), ('Wrong Direction', 'Wrong Direction'), ('Missed', 'Missed')], default='Pending', max_length=20)),
                ('execution_rate', models.FloatField(default=0)),
                ('webhook_payload', models.JSONField(blank=True, default=dict, help_text='Raw TradingView payload')),
                ('webhook_secret_valid', models.BooleanField(default=False)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'signals',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
    ]
