# Generated by Django 5.1.5 on 2026-07-22 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_tradingsignal_signal_assigned_to_signal_deleted_at_and_more'),
        ('users', '0004_traderprofile_user_created_at_user_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='trader_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='users.traderprofile'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['session_date', 'status'], name='signals_session_ee292d_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['pair', 'direction'], name='signals_pair_1aa865_idx'),
        ),
    ]
