# Generated by Django 5.1.5 on 2026-07-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_signal_trader_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='fib_0236',
            field=models.FloatField(blank=True, help_text='Entry 1 price at Fib 0.236', null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='fib_0500',
            field=models.FloatField(blank=True, help_text='Entry 2 price at Fib 0.500', null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='fib_0618',
            field=models.FloatField(blank=True, help_text='Entry 3 price at Fib 0.618', null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='fib_entry',
            field=models.FloatField(blank=True, help_text='Primary entry Fib level label e.g. 0.236, 0.5, 0.618 (informational)', null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='fib_tp',
            field=models.FloatField(blank=True, help_text='TP price at Fib -0.27 extension (alias of take_profit)', null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='stop_loss',
            field=models.FloatField(help_text='SL price at Fib 0.786'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='take_profit',
            field=models.FloatField(help_text='TP price at Fib -0.27 extension'),
        ),
    ]
