# Generated by Django 5.1.5 on 2026-07-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_account_number_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complianceScore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='entryAccuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='executionRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lateEntries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='timingAccuracy',
            field=models.FloatField(default=0),
        ),
    ]
