# Generated by Django 5.1.5 on 2026-07-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='MIKAPEDIA Capital', max_length=100)),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('tv_webhook_url', models.URLField(blank=True)),
                ('mt5_bridge_host', models.CharField(blank=True, max_length=255)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('session_open_utc', models.TimeField(default='07:00')),
                ('session_close_utc', models.TimeField(default='21:00')),
                ('attendance_cutoff', models.TimeField(default='09:15')),
                ('office_gps_radius_m', models.IntegerField(default=120)),
                ('fib_entry_a', models.FloatField(default=0.236)),
                ('fib_entry_b', models.FloatField(default=0.5)),
                ('fib_entry_c', models.FloatField(default=0.618)),
                ('take_profit_fib', models.FloatField(default=-0.27)),
                ('max_entry_delay_minutes', models.IntegerField(default=10)),
                ('max_lot_per_trade', models.FloatField(default=0.5)),
                ('auto_reject_wrong_direction', models.BooleanField(default=True)),
                ('notify_on_missed_signal', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
